name: Linux (ubuntu-22.04)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        compiler: [clangd, gcc]
        include:
          - compiler: clang
            env: CC=clang-20 CXX=clang++-20
          - compiler: gcc
            env: CC=/usr/local/bin/gcc CXX=/usr/local/bin/g++
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup required packages'
        run: |
          sudo apt-get update
          sudo ./pkg-dependency.sh

      - if: ${{ matrix.compiler == 'gcc'}}
        name: "Setup gcc"
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 12

      - if: ${{ matrix.compiler == 'clang'}}
        name: "Setup clang"
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 20

      - name: 'Setup cmake'
        run: cmake --version

      - name: 'Setup git submodule'
        run: git submodule update --init --recursive

      - name: 'Build and test'
        env:
          # Make sanitizers abort on errors instead of just printing warnings
          UBSAN_OPTIONS: halt_on_error=1:print_stacktrace=1
          ASAN_OPTIONS: halt_on_error=1:print_stacktrace=1
        run: |
          export ${{matrix.env}}
          mkdir build.debug && cd build.debug
          cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
          ninja fbe-tests smoke_tests
          ./fbe-tests && ./smoke_tests/smoke_tests
